version: '2'
services:
  bootnode:
    image: ${IMAGE}
    entrypoint: bash
    ports:
      - 9000
      - 30303
      - 30301
    networks:
      app_net:
        ipv4_address: 172.19.0.200
    cap_add:
      - ALL
    tty: true
    volumes:
      - ${VOLUME_PATH}
    privileged: true
    command: -c "cd ../workspace &&
        tc qdisc add dev eth0 root netem delay ${NET_DELAY} 20ms distribution normal &&
        bootnode --nodekey=boot.key --verbosity 9 2>> bootnode.txt &&
        /bin/bash"

  miner1:
    image: ${IMAGE}
    entrypoint: bash
    tty: true
    ports:
      - 9000
      - 30303
      - 30301
      - 8545
    networks:
      app_net:
        ipv4_address: 172.19.0.100
    volumes:
        - ${VOLUME_PATH}
    privileged: true
    command: -c "cd ../workspace &&
        tc qdisc add dev eth0 root netem delay ${NET_DELAY} 20ms distribution normal &&
        geth --datadir miner1 --networkid 1234 init genesisTesting.json 2>> miner1.txt  &&
        geth --datadir miner1 --networkid 1234 --exec 'personal.newAccount("\"1234"\")' console 2>> miner1.txt &&
        geth --datadir miner1 --networkid 1234 --verbosity 6 --exec 'personal.unlockAccount(eth.accounts[0], "\"1234"\", 10000)' --bootnodes "enode://8a080f000641843af0e117381feb090677ef7d674448e6d3b94f7d3fda46f3c52a727ab9113a9c5c7bf6cb09addc3e3ffbe4f8d4b55ee174d3bd683746e0d638@[172.19.0.200]:30301" --mine --minerthreads 1 --rpc --rpcapi \"admin, eth, personal, miner, txpool, net, web3\" 2>> miner1.txt &&
        bin/bash"

  miner2:
    image: ${IMAGE}
    entrypoint: bash
    tty: true
    ports:
      - 9000
      - 30303
      - 30301
      - 8545
    networks:
      app_net:
        ipv4_address: 172.19.0.101
    volumes:
        - ${VOLUME_PATH}
    privileged: true
    command: -c "cd ../workspace &&
        tc qdisc add dev eth0 root netem delay ${NET_DELAY} 20ms distribution normal &&
        geth --datadir miner2 --networkid 1234 init genesisTesting.json 2>> miner2.txt  &&
        geth --datadir miner2 --networkid 1234 --exec 'personal.newAccount("\"1234"\")' console 2>> miner2.txt &&
        geth --datadir miner2 --networkid 1234 --verbosity 6 --exec 'personal.unlockAccount(eth.accounts[0], "\"1234"\", 10000)' --bootnodes "enode://8a080f000641843af0e117381feb090677ef7d674448e6d3b94f7d3fda46f3c52a727ab9113a9c5c7bf6cb09addc3e3ffbe4f8d4b55ee174d3bd683746e0d638@[172.19.0.200]:30301" --mine --minerthreads 1 --rpc --rpcapi \"admin, eth, personal, miner, txpool, net, web3\" 2>> miner2.txt &&
        bin/bash"

  node1:
    image: ${IMAGE}
    entrypoint: bash
    tty: true
    ports:
      - 9000
      - 30303
      - 30301
    networks:
      app_net:
        ipv4_address: 172.19.0.2
    volumes:
        - ${VOLUME_PATH}
    privileged: true
    command: -c "cd ../workspace &&
        tc qdisc add dev eth0 root netem delay ${NET_DELAY} 20ms distribution normal &&
        geth --datadir node1 --networkid 1234 init genesisTesting.json console 2>> node1.txt  &&
        geth --datadir node1 --networkid 1234 --verbosity 6 --bootnodes "enode://8a080f000641843af0e117381feb090677ef7d674448e6d3b94f7d3fda46f3c52a727ab9113a9c5c7bf6cb09addc3e3ffbe4f8d4b55ee174d3bd683746e0d638@[172.19.0.200]:30301" 2>> node1.txt  &&
        /bin/bash"

  node2:
    image: ${IMAGE}
    entrypoint: bash
    tty: true
    ports:
      - 9000
      - 30303
      - 30301
    networks:
      app_net:
        ipv4_address: 172.19.0.3
    volumes:
        - ${VOLUME_PATH}
    privileged: true
    command: -c "cd ../workspace &&
        tc qdisc add dev eth0 root netem delay ${NET_DELAY} 20ms distribution normal &&
        geth --datadir node2 --networkid 1234 init genesisTesting.json console 2>> node2.txt  &&
        geth --datadir node2 --networkid 1234 --verbosity 6 --bootnodes "enode://8a080f000641843af0e117381feb090677ef7d674448e6d3b94f7d3fda46f3c52a727ab9113a9c5c7bf6cb09addc3e3ffbe4f8d4b55ee174d3bd683746e0d638@[172.19.0.200]:30301" 2>> node2.txt  &&
        /bin/bash"

  node3:
    image: ${IMAGE}
    entrypoint: bash
    tty: true
    ports:
      - 9000
      - 30303
      - 30301
    networks:
      app_net:
        ipv4_address: 172.19.0.4
    volumes:
        - ${VOLUME_PATH}
    privileged: true
    command: -c "cd ../workspace &&
        tc qdisc add dev eth0 root netem delay ${NET_DELAY} 20ms distribution normal &&
        geth --datadir node3 --networkid 1234 init genesisTesting.json console 2>> node3.txt  &&
        geth --datadir node3 --networkid 1234 --verbosity 6 --bootnodes "enode://8a080f000641843af0e117381feb090677ef7d674448e6d3b94f7d3fda46f3c52a727ab9113a9c5c7bf6cb09addc3e3ffbe4f8d4b55ee174d3bd683746e0d638@[172.19.0.200]:30301" 2>> node3.txt  &&
        /bin/bash"

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::/1
