version: '2'
services:
  miner0:
    image: test
    entrypoint: bash
    command: -c "mkdir -p code && /bin/bash"
    tty: true
    ports:
      - 9000
    networks:
      app_net:
        ipv4_address: 192.168.0.2
  user0:
    image: test
    entrypoint: bash
    command: -c "mkdir -p code && /bin/bash"
    tty: true
    ports:
      - 9000
    networks:
      app_net:
        ipv4_address: 192.168.0.3
  user1:
    image: test
    entrypoint: bash
    command: -c "mkdir -p code && /bin/bash"
    tty: true
    ports:
      - 9000
    networks:
      app_net:
        ipv4_address: 192.168.0.4
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::/1
  miner0:
    image: test
    entrypoint: bash
    command: -c "mkdir -p code && /bin/bash"
    tty: true
    ports:
      - 9000
    networks:
      app_net:
        ipv4_address: 192.168.0.2
  user0:
    image: test
    entrypoint: bash
    command: -c "mkdir -p code && /bin/bash"
    tty: true
    ports:
      - 9000
    networks:
      app_net:
        ipv4_address: 192.168.0.3
  user1:
    image: test
    entrypoint: bash
    command: -c "mkdir -p code && /bin/bash"
    tty: true
    ports:
      - 9000
    networks:
      app_net:
        ipv4_address: 192.168.0.4
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::/1
